language: go
go_import_path: github.com/gallactic/gallactic
sudo: false
matrix:
  include:
    - os: linux
      dist: trusty
      go: 1.10.x
      before_install:
        # installing rust and cargo
        - curl https://sh.rustup.rs -sSf | sh
      script:
        - make


    - os: osx
      go: 1.10.x
      before_install:
        # installing rust and cargo
        - curl https://sh.rustup.rs -sSf | sh
      script:
        - make
