[[override]]
  name = "github.com/tendermint/tendermint"
  version = "=0.30.0"

[[override]]
  name = "github.com/tendermint/go-amino"
  version = "=0.14.1"

[[override]]
  name = "github.com/tendermint/iavl"
  version = "=0.12.0"

[[override]]
  name = "github.com/gogo/protobuf"
  version = "~1.2.0"

[[override]]
  name = "github.com/golang/protobuf"
  version = "~1.2.0"

[[override]]
  name = "google.golang.org/grpc"
  version = "~1.18.0"

[[constraint]]
  name = "golang.org/x/crypto"
  revision = "505ab145d0a99da450461ae2c1a9f6cd10d1f447"


[[override]]
  name = "golang.org/x/net"
  revision = "292b43bbf7cb8d35ddf40f8d5100ef3837cced3f"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

    [[prune.project]]
      name = "github.com/gallactic/sputnikvm-ffi"
      unused-packages = false